/**
 * tests/e2e/helpers.ts — Shared E2E test utilities.
 *
 * Provides functions to inject authenticated session cookies into
 * Playwright browser contexts, simulating Google OAuth login without
 * hitting real Google endpoints.
 */

import { readFileSync } from "fs";
import { resolve } from "path";
import type { BrowserContext, Page } from "@playwright/test";

const E2E_DIR = resolve(__dirname);

/**
 * Read the signed session cookie generated by run_test_server.py.
 */
export function getTestSessionCookie(): string {
  const cookieFile = resolve(E2E_DIR, ".test-session-cookie");
  return readFileSync(cookieFile, "utf-8").trim();
}

/**
 * Read the test user ID generated by run_test_server.py.
 */
export function getTestUserId(): string {
  const idFile = resolve(E2E_DIR, ".test-user-id");
  return readFileSync(idFile, "utf-8").trim();
}

/**
 * Inject the test session cookie into a browser context,
 * simulating an authenticated user.
 */
export async function loginAsTestUser(context: BrowserContext): Promise<void> {
  const cookieValue = getTestSessionCookie();
  await context.addCookies([
    {
      name: "cpet_session",
      value: cookieValue,
      domain: "localhost",
      path: "/",
      httpOnly: true,
      sameSite: "Lax",
    },
  ]);
}

/**
 * Clear the session cookie to simulate a logged-out user.
 */
export async function logout(context: BrowserContext): Promise<void> {
  await context.clearCookies();
}

/**
 * Navigate to a page and wait for the network to be idle.
 */
export async function navigateAndWait(
  page: Page,
  path: string,
): Promise<void> {
  await page.goto(path, { waitUntil: "networkidle" });
}
